### ISSUE TITLE
Proxy issue?

### ISSUE THREAD

**Issue by ToasterWaffl** [Degen-dev/Degeneracy#12] opened 2022-02-28 17:55 UTC
Proxy issue with womngix 
Go to the website and click womgix then click discord , the website returns a blank white page 
Is this a issue with womgnix?

**Comment by Degen-dev** [comment] 2022-02-28 18:26
Is this issue occurring for you on all of the links, or just one?

**Comment by ToasterWaffl** [comment] 2022-02-28 18:26
Mainly womgnix I can’t use captcha with rhodium

**Comment by Degen-dev** [comment] 2022-02-28 18:29
Could you post the url you are using for Degeneracy?

**Comment by ToasterWaffl** [comment] 2022-02-28 18:29
pleasedontblock.me

**Comment by ToasterWaffl** [comment] 2022-02-28 18:33
I’m using iOS this happened before with another proxy

**Comment by Degen-dev** [comment] 2022-02-28 18:43
On iOS, I was able to recreate the issue. It appears that womginx itself doesn't work on iOS browsers i.e. Safari. I will see what I can do about this, maybe reverting back to an older version of womginx.

**Comment by ToasterWaffl** [comment] 2022-02-28 19:10
A older version of womgnix worked before

**Comment by Degen-dev** [comment] 2022-03-03 18:07
It looks like womginx has gotten a commit that fixed this. I will apply this to my instance as soon as possible.

**Comment by Degen-dev** [comment] 2022-03-04 06:49
I have updated womginx to the latest commit, and discord now works on my iOS device. Please alert me on whether or not it works for you now.

**Comment by ToasterWaffl** [comment] 2022-03-08 18:13
It’s working on my end

**Comment by ToasterWaffl** [comment] 2022-03-08 18:15
It was working I can still access discord so it’s working on your end I think womginx in general is suffering

**Comment by ToasterWaffl** [comment] 2022-03-08 18:45
It works

**Comment by Degen-dev** [comment] 2022-03-08 18:50
Nice! I will be closing this issue now, as the issue is resolved.

**Closed by Degen-dev** 2022-03-08 18:50 UTC
Labels: bug, enhancement
